import Marquee from 'react-fast-marquee';

const Header = () => (
  // will need to take this many to fit in 25% zoomed out on chrome for 4k
  <div className="my-2">
    <Marquee speed={50} gradient={false} direction="left">
      WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @
      WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @
      WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA
      WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @
      WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @
      WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA
      WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @
      WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @
      WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA
      WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @
      WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @
      WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA
      WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @
      WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @
      WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA
      WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @
      WELCOME TO INDRA @ WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @
      WELCOME TO INDRA WELCOME TO INDRA @ WELCOME TO INDRA @ WELCOME TO INDRA
    </Marquee>
  </div>
);

export default Header;
